221004/practice/crud/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("post/", include("posts.urls")),
]

221004/practice/posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path("", views.index, name="index"),
    path("new", views.new, name="new"),
    path("create", views.create, name="create"),
]

221004/practice/posts/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    create_at = models.DateField(auto_now_add=True)
    update_at = models.DateField(auto_now=True)

221004/practice/posts/views.py
from django.shortcuts import render, redirect
from .models import Post

# Create your views here.
def index(request):
    posts = Post.objects.all()
    return render(request, "posts/index.html", {"posts": posts})


def new(request):
    return render(request, "posts/new.html")


def create(request):
    title = request.POST.get("title")
    content = request.POST.get("content")
    return redirect("posts:index")

221004/practice/crud/templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>
  {% block content %}
  {% endblock %}
</body>

</html>

221004/practice/posts/templates/posts/index.html
{% extends 'base.html' %}

{% block content %}
<h1>글 목록</h1>
<a href="{% url 'posts:new' %}">글 작성하기</a>

{% for post in posts %}

<p>{{ post.title }} {{ post.create_at}}</p>

{% endfor%}

{% endblock %}

221004/practice/posts/templates/posts/new.html
{% extends 'base.html' %}

{% block content %}

<form action="{% url 'posts:create' %}" method="post">
  제목 : <input type="text" name="title"><br>
  내용 : <input type="text" name="content">
  <button type="submit">작성완료</button>
</form>

{% endfor%}

{% endblock %}